=== MarketaTest/fopengine-test-repository_2/src/main/resources/GeneratorConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 2 (x64) (http://www.altova.com) by Robert Wachter (IRS GmbH) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:attributeGroup name="file">
		<xs:attribute name="source-path" type="xs:string">
			<xs:annotation>
				<xs:documentation>link to file in jar</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="target-path" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>target folder in Genera</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:attributeGroup>
	<xs:attributeGroup name="mavenArtifact">
		<xs:attribute name="group" type="xs:string" use="required"/>
		<xs:attribute name="artifact" type="xs:string" use="required"/>
		<xs:attribute name="version" type="xs:string" use="required"/>
	</xs:attributeGroup>
	<xs:element name="Configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Userconfig" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="File"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="Jobs"/>
				<xs:element ref="Fonts" minOccurs="0"/>
				<xs:element ref="Transformations" minOccurs="0"/>
				<xs:element ref="Services" minOccurs="0"/>
				<xs:element ref="WorkFlow"/>
				<xs:element ref="Templates" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="project-name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string"/>
			<xs:attributeGroup ref="mavenArtifact"/>
			<xs:attribute name="self-contained" type="xs:boolean" default="false">
				<xs:annotation>
					<xs:documentation>true if project should be unpacked from resources at start of application</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Processor">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="class" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Postprocessors">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Processor" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Step">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Preprocessors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Processor" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="Transformers" minOccurs="0"/>
				<xs:element ref="Postprocessors" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="step-key" type="xs:string" use="required"/>
			<xs:attribute name="output-file-mask"/>
			<xs:attribute name="input-type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="file"/>
						<xs:enumeration value="source"/>
						<xs:enumeration value="string"/>
						<xs:enumeration value="internal"/>
						<xs:enumeration value="output_stream"/>
						<xs:enumeration value="input_stream"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="output-type" use="required">
				<xs:annotation>
					<xs:documentation>output type </xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="file"/>
						<xs:enumeration value="output_stream"/>
						<xs:enumeration value="string"/>
						<xs:enumeration value="internal"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Transformer">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="class" type="xs:string" use="required"/>
			<xs:attributeGroup ref="object-type"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Transformers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Transformer" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="object-type">
		<xs:attribute name="object-type" type="xs:string" use="required"/>
	</xs:attributeGroup>
	<xs:element name="Processes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Process" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Process">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="StepLink" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="StepLink">
		<xs:complexType>
			<xs:attribute name="step-key" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Template">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Main-template">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="File"/>
							<xs:element name="Template-files" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="File" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="Graphics" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="template-name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Modules">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Module" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Settings">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Fop" minOccurs="0">
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element ref="Module"/>
						</xs:sequence>
						<xs:attribute name="pdflib-enabled" type="xs:boolean" use="required">
							<xs:annotation>
								<xs:documentation>usage of pdfLib is enabled</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="pdflib-version" type="xs:string">
							<xs:annotation>
								<xs:documentation>pdfLib version</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element ref="Modules" minOccurs="0"/>
				<xs:element ref="Entries" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Font">
		<xs:complexType>
			<xs:sequence maxOccurs="4">
				<xs:element ref="Font-triplet"/>
			</xs:sequence>
			<xs:attribute name="font-name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Transformation">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element ref="Main-xsl" minOccurs="0"/>
				<xs:element ref="Graphics" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="xsl"/>
						<xs:enumeration value="generator"/>
						<xs:enumeration value="layout"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="description"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Module">
		<xs:complexType>
			<xs:attribute name="name"/>
			<xs:attributeGroup ref="mavenArtifact"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Transformations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Transformation" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Fonts">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Font" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Font-triplet">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Metrics-file">
					<xs:complexType>
						<xs:attributeGroup ref="file"/>
						<xs:attribute name="file-name" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element ref="File" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="font-style" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="normal"/>
						<xs:enumeration value="italic"/>
						<xs:enumeration value="bold"/>
						<xs:enumeration value="bolditalic"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="indd-name"/>
			<xs:attribute name="indd-style"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Xsls">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="File" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Main-xsl">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="File"/>
				<xs:element ref="Xsls" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Main-schema">
		<xs:annotation>
			<xs:documentation>main schema file</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="File"/>
				<xs:element ref="Schemas" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Schemas">
		<xs:annotation>
			<xs:documentation>further schemas which are necessery for imports from other schemas</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="File" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Graphics">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="File" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="File">
		<xs:complexType>
			<xs:attribute name="file-name" use="required"/>
			<xs:attributeGroup ref="file"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Entry">
		<xs:complexType>
			<xs:attribute name="key" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Entries">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Entry" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Auxiliary-services">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Auxiliary-service" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Auxiliary-service">
		<xs:complexType>
			<xs:attribute name="service-key" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Services">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Service" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Service">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Auxiliary-services" minOccurs="0"/>
				<xs:element ref="Entries" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="service-key" type="xs:string" use="required"/>
			<xs:attribute name="builder-class" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="WorkFlow">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Processes"/>
				<xs:element ref="Steps" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Steps">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Step" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Template" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Jobs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Job" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Job">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Main-schema" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="job-name" type="xs:string" use="required"/>
			<xs:attribute name="process-name" type="xs:string" use="required"/>
			<xs:attribute name="transformation-name" type="xs:string"/>
			<xs:attribute name="template-name"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MarketaTest/fopengine-test-repository_2/src/main/resources/fopengine/fopengine-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration xsi:noNamespaceSchemaLocation="../../../main/resources/GeneratorConfiguration.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" artifact="test-genera" project-name="testProject 2" group="de.irs.fopengine" version="0.01"  description="This is a great project 2" self-contained="false">
	<Userconfig>
		<File file-name="userconfig.xml" target-path="conf"/>
	</Userconfig>
	<Jobs>
		<Job job-name="genera_idml" process-name="GENERATE_IDML">
			<Main-schema>
				<File file-name="Genera5DataDynamic.xsd" source-path="schema" target-path="schema"/>
				<Schemas>
					<File file-name="Genera5HtmlText.xsd" source-path="schema" target-path="schema"/>
				</Schemas>
			</Main-schema>
		</Job>
		<Job job-name="xsl_fo" process-name="GENERATE_XSL_FO" transformation-name="genera">
			<Main-schema>
				<File file-name="Genera5DataDynamic.xsd" source-path="schema" target-path="schema"/>
				<Schemas>
					<File file-name="Genera5HtmlText.xsd" source-path="schema" target-path="schema"/>
					<File file-name="Genera4HtmlText.xsd" source-path="schema2" target-path="schema2"/>
				</Schemas>
			</Main-schema>
		</Job>
		<Job job-name="xsl_fo" process-name="GENERATE_XSL_FO" transformation-name="genera2"/>
		<Job job-name="template" process-name="TEMPLATE_PDF" template-name="template1">
			<Main-schema>
				<File file-name="Template.xsd" source-path="schema" target-path="schema"/>
			</Main-schema>
		</Job>
	</Jobs>
	<Fonts>
		<!--  __________________________________________________________ -->
		<!--                                           ArialUnicode      -->
		<!--  __________________________________________________________ -->
		<Font font-name="arialuni">
			<Font-triplet indd-name="Arial Unicode MS" indd-style="Regular" font-style="normal">
				<Metrics-file file-name="arialuni.xml" target-path="fonts"/>
				<File file-name="arialuni.ttf" target-path="fonts"/>
			</Font-triplet>
		</Font>
		<!--  __________________________________________________________ -->
		<!--                                           JCArial           -->
		<!--  __________________________________________________________ -->
		<Font font-name="Arial">
			<Font-triplet indd-name="Arial" indd-style="Regular" font-style="normal">
				<Metrics-file file-name="arial.xml" target-path="fonts"/>
				<File file-name="arial.ttf" target-path="fonts"/>
			</Font-triplet>
			<Font-triplet indd-name="Arial" indd-style="Bold" font-style="bold">
				<Metrics-file file-name="arialb.xml" target-path="fonts"/>
				<File file-name="arialb.ttf" target-path="fonts"/>
			</Font-triplet>
			<Font-triplet indd-name="Arial" indd-style="Italic" font-style="italic">
				<Metrics-file file-name="ariali.xml" target-path="fonts"/>
				<File file-name="ariali.ttf" target-path="fonts"/>
			</Font-triplet>
		</Font>
		<!--  __________________________________________________________ -->
		<!--                                           JCArialBold       -->
		<!--  __________________________________________________________ -->
		<Font font-name="ArialBold">
			<Font-triplet indd-name="Arial" indd-style="Bold" font-style="normal">
				<Metrics-file file-name="arial.xml" target-path="fonts"/>
				<File file-name="arial.ttf" target-path="fonts"/>
			</Font-triplet>
			<Font-triplet indd-name="Arial" indd-style="Black" font-style="bold">
				<Metrics-file file-name="arialb.xml" target-path="fonts"/>
				<File file-name="arialb.ttf" target-path="fonts"/>
			</Font-triplet>
			<Font-triplet indd-name="Arial" indd-style="Bold Italic" font-style="bolditalic">
				<Metrics-file file-name="arialbi.xml" target-path="fonts"/>
				<File file-name="arialbi.ttf" target-path="fonts"/>
			</Font-triplet>
		</Font>
		<!--  __________________________________________________________ -->
		<!--                                           JCArialBlack      -->
		<!--  __________________________________________________________ -->
		<Font font-name="JCArialBlack">
			<Font-triplet indd-name="Arial" indd-style="Black" font-style="normal">
				<Metrics-file file-name="ariblk.xml" target-path="fonts"/>
				<File file-name="ariblk.ttf" target-path="fonts"/>
			</Font-triplet>
			<Font-triplet indd-name="Arial" indd-style="Black" font-style="bold">
				<Metrics-file file-name="ariblk.xml" target-path="fonts"/>
				<File file-name="ariblk.ttf" target-path="fonts"/>
			</Font-triplet>
			<Font-triplet indd-name="Arial" indd-style="Black Italic" font-style="italic">
				<Metrics-file file-name="ariblki.xml" target-path="fonts"/>
				<File file-name="ariblki.ttf" target-path="fonts"/>
			</Font-triplet>
			<Font-triplet indd-name="Arial" indd-style="Black Italic" font-style="bolditalic">
				<Metrics-file file-name="ariblki.xml" target-path="fonts"/>
				<File file-name="ariblki.ttf" target-path="fonts"/>
			</Font-triplet>
		</Font>
		<!--  __________________________________________________________ -->
		<!--                                           HelveticaLight			   						     -->
		<!--  __________________________________________________________ -->
		<Font font-name="Helvetica">
			<Font-triplet indd-name="Courier New" indd-style="Regular" font-style="normal">
				<Metrics-file file-name="LTe50263_IRS.xml" target-path="fonts"/>
				<File file-name="LTe50263_IRS.pfb" target-path="fonts"/>
				<File file-name="LTe50263_IRS.pfm" target-path="fonts"/>
			</Font-triplet>
			<Font-triplet indd-name="Courier New" indd-style="Bold" font-style="bold">
				<Metrics-file file-name="LTe50265.xml" target-path="fonts"/>
				<File file-name="LTe50265.pfb" target-path="fonts"/>
				<File file-name="LTe50265.pfm" target-path="fonts"/>
			</Font-triplet>
			<Font-triplet indd-name="Courier New" indd-style="Italic" font-style="italic">
				<Metrics-file file-name="" target-path="fonts/LTe50264.xml"/>
				<File file-name="LTe50264.pfb" target-path="fonts"/>
				<File file-name="LTe50264.pfm" target-path="fonts"/>
			</Font-triplet>
			<Font-triplet indd-name="Courier New" indd-style="Bold Italic" font-style="bolditalic">
				<Metrics-file file-name="LTe50266.xml" target-path="fonts"/>
				<File file-name="LTe50266.pfb" target-path="fonts"/>
				<File file-name="LTe50266.pfm" target-path="fonts"/>
			</Font-triplet>
		</Font>
	</Fonts>
	<Transformations>
		<Transformation name="genera" type="xsl" description="test transformation 1">
			<Main-xsl>
				<File file-name="genera5.xsl" target-path="conf" source-path="conf"/>
				<Xsls>
					<File file-name="main.xsl" target-path="conf" source-path="conf"/>
					<File file-name="crop_marks.xsl" target-path="conf" source-path="conf"/>
				</Xsls>
			</Main-xsl>
		</Transformation>
		<Transformation name="genera2" type="xsl">
			<Main-xsl>
				<File file-name="genera5.xsl" target-path="conf" source-path="conf"/>
			</Main-xsl>
			<Graphics>
				<File target-path="img" file-name="img1.jpg"></File>
				<File target-path="img" file-name="img2.jpg"></File>
			</Graphics>
		</Transformation>
	</Transformations>

	<Services>
		<Service service-key="pdf-output" builder-class="de.irs.generator.services.fop.PdfServiceBuilder"/>
		<Service service-key="xsl-service" builder-class="de.irs.generator.services.xsl.XslServiceBuilder">
			<Auxiliary-services>
				<Auxiliary-service service-key="char-convert-service"/>
			</Auxiliary-services>
		</Service>
		<Service service-key="char-convert-service" builder-class="de.irs.generator.services.charConvertService.CharConvertServiceBuilder"/>
		<Service service-key="idml-service" builder-class="de.irs.generator.services.idml.IdmlServiceBuilder"/>
	</Services>
	<WorkFlow>
		<Processes>
			<Process name="GENERATE_IDML">
				<StepLink step-key="READ_GENERA_XML_FOR_IDML"/>
				<StepLink step-key="STEP_INDESIGN_OUTPUT"/>
			</Process>
			<Process name="GENERATE_XSL_FO">
				<StepLink step-key="STEP_XSL_CONVERT"/>
			</Process>
		</Processes>
		<Steps>
			<Step step-key="STEP_XSL_CONVERT" output-file-mask="%%job-id%%_fo.fo" input-type="file" output-type="output_stream">
				<Transformers>
					<Transformer name="document" object-type="DOCUMENT" class="de.irs.generator.services.xsl.XslTransformer"/>
				</Transformers>
			</Step>
			<Step step-key="READ_GENERA_XML" input-type="file" output-type="internal" output-file-mask="%%job-id%%_layout.xml">
				<Transformers>
					<Transformer name="document" object-type="DOCUMENT" class="de.irs.generator.genera.transformers.GeneraReaderTransformer" description="konvertuje data z xml do Generator structure"/>
				</Transformers>
			</Step>
			<Step step-key="READ_GENERA_XML_FOR_IDML" input-type="file" output-type="internal" output-file-mask="%%job-id%%_layout.xml">
				<Transformers>
					<Transformer name="document" object-type="DOCUMENT" class="de.irs.generator.genera.transformers.GeneraReaderTransformer"/>
				</Transformers>
				<Postprocessors>
					<Processor name="document xCorrection and yCorrection" class="de.irs.generator.genera.processors.CorrectionPP"/>
				</Postprocessors>
			</Step>
			<Step step-key="STEP_INDESIGN_OUTPUT" input-type="internal" output-type="file" output-file-mask="%%job-id%%_indd.xml">
				<Preprocessors>
					<Processor name="make the spans" class="de.irs.generator.output.indd.processors.ProcessSpanPP"/>
				</Preprocessors>
				<Transformers>
					<Transformer name="" object-type="" class="de.irs.generator.output.indd.inddTransformers.InddDocumentTransformer"/>
				</Transformers>
				<Postprocessors>
					<Processor name="prepare redefined paragraph styles" class="de.irs.generator.output.indd.processors.ConsolideCharStylesPP"/>
				</Postprocessors>
			</Step>
		</Steps>
	</WorkFlow>
	<Templates>
		<Template template-name="template1">
			<Main-template>
				<File source-path="templates" target-path="templates" file-name="template1.xml"/>
				<Template-files>
					<File source-path="templates" target-path="templates" file-name="styles.xml"></File>
